export const USER_ERROR_CODES = {
    ALREADY_EXISTS: "USER_A006",
    EMAIL_UNVERIFIED: "USER_A011",
    INVALID_OTP: "USER_A012",
    OTP_COOLDOWN: "USER_A013",
    OTP_ATTEMPTS_EXCEEDED: "USER_A014",
} as const;
