export const USER_ERROR_CODES = {
    NOT_FOUND: "USER_A003",
    ALREADY_EXISTS: "USER_A006",
    EMAIL_UNVERIFIED: "USER_A011",
    INVALID_OTP: "USER_A012",
    OTP_COOLDOWN: "USER_A013",
    OTP_ATTEMPTS_EXCEEDED: "USER_A014",
    PASSWORD_NOT_MATCH: "USER_A015",
    PASSWORD_SAME_AS_OLD: "USER_A017",
    INVALID_RESET_TOKEN: "USER_A019",
    SOCIAL_LOGIN_CANNOT_RESET_PASSWORD: "USER_A020",
} as const;
