export interface SettingSearchItem {
    id: string;
    settingId: string;
    route: string;
    partKey: "general" | "account" | "security" | "billing";
    titleKey: string;
    descriptionKey: string;
    keywords: string[];
}

export const SETTINGS_SEARCH_REGISTRY: SettingSearchItem[] = [
    {
        id: "appearance",
        settingId: "setting-appearance",
        route: "/settings",
        partKey: "general",
        titleKey: "settings.general.appearanceTitle",
        descriptionKey: "settings.general.appearanceDesc",
        keywords: [
            "giao diện",
            "giao dien",
            "dark mode",
            "light mode",
            "sáng",
            "tối",
            "chỉnh màu",
            "màu sắc",
            "theme",
            "appearance",
            "mode",
            "giao diện tối",
            "giao diện sáng",
            "システム設定",
            "外観",
            "ダークモード",
            "ライトモード",
        ],
    },
    {
        id: "language",
        settingId: "setting-language",
        route: "/settings",
        partKey: "general",
        titleKey: "settings.general.languageTitle",
        descriptionKey: "settings.general.languageDesc",
        keywords: [
            "ngôn ngữ",
            "ngon ngu",
            "language",
            "đổi ngôn ngữ",
            "tiếng việt",
            "tiếng anh",
            "tiếng nhật",
            "english",
            "vietnamese",
            "japanese",
            "ngôn ngữ hiển thị",
            "言語",
            "表示言語",
        ],
    },
    {
        id: "avatar",
        settingId: "setting-avatar",
        route: "/settings/account",
        partKey: "account",
        titleKey: "settings.account.avatarTitle",
        descriptionKey: "settings.account.avatarDesc",
        keywords: [
            "avatar",
            "ảnh đại diện",
            "anh dai dien",
            "ảnh",
            "image",
            "picture",
            "photo",
            "đổi ảnh",
            "thay ảnh",
            "xóa ảnh",
            "プロフィール画像",
            "画像",
        ],
    },
    {
        id: "email",
        settingId: "setting-email",
        route: "/settings/account",
        partKey: "account",
        titleKey: "settings.account.emailLabel",
        descriptionKey: "settings.account.emailDesc",
        keywords: [
            "email",
            "địa chỉ email",
            "dia chi email",
            "hòm thư",
            "tài khoản email",
            "email address",
            "mail",
            "メールアドレス",
        ],
    },
    {
        id: "fullname",
        settingId: "setting-fullname",
        route: "/settings/account",
        partKey: "account",
        titleKey: "settings.account.fullNameLabel",
        descriptionKey: "settings.account.profileDesc",
        keywords: [
            "họ và tên",
            "ho va ten",
            "họ tên",
            "ho ten",
            "full name",
            "name",
            "tên người dùng",
            "tên",
            "氏名",
            "名前",
        ],
    },
    {
        id: "gender",
        settingId: "setting-gender",
        route: "/settings/account",
        partKey: "account",
        titleKey: "settings.account.genderLabel",
        descriptionKey: "settings.account.profileDesc",
        keywords: [
            "giới tính",
            "gioi tinh",
            "gender",
            "nam",
            "nữ",
            "khác",
            "sex",
            "male",
            "female",
            "性別",
        ],
    },
    {
        id: "dob",
        settingId: "setting-dob",
        route: "/settings/account",
        partKey: "account",
        titleKey: "settings.account.dobLabel",
        descriptionKey: "settings.account.profileDesc",
        keywords: [
            "ngày sinh",
            "ngay sinh",
            "dob",
            "date of birth",
            "birthdate",
            "sinh nhật",
            "năm sinh",
            "生年月日",
            "誕生日",
        ],
    },
    {
        id: "jlpt",
        settingId: "setting-jlpt",
        route: "/settings/account",
        partKey: "account",
        titleKey: "settings.account.jlptLabel",
        descriptionKey: "settings.account.jlptDesc",
        keywords: [
            "jlpt level",
            "jlpt",
            "trình độ",
            "trinh do",
            "tiếng nhật",
            "trình độ tiếng nhật",
            "n5",
            "n4",
            "n3",
            "n2",
            "n1",
            "level",
            "JLPTレベル",
            "日本語能力",
        ],
    },
    {
        id: "update-profile",
        settingId: "setting-update-profile",
        route: "/settings/account",
        partKey: "account",
        titleKey: "settings.account.updateProfileBtn",
        descriptionKey: "settings.account.profileDesc",
        keywords: [
            "cập nhật thông tin",
            "cap nhat thong tin",
            "lưu thông tin",
            "cập nhật hồ sơ",
            "update profile",
            "save profile",
            "thông tin cá nhân",
            "情報を更新",
        ],
    },
    {
        id: "delete-account",
        settingId: "setting-delete-account",
        route: "/settings/account",
        partKey: "account",
        titleKey: "settings.account.deleteAccountTitle",
        descriptionKey: "settings.account.deleteAccountDesc",
        keywords: [
            "xóa tài khoản",
            "xoa tai khoan",
            "delete account",
            "hủy tài khoản",
            "xóa nick",
            "xóa hồ sơ",
            "remove account",
            "danger zone",
            "vùng nguy hiểm",
            "アカウント削除",
        ],
    },
    {
        id: "change-password",
        settingId: "setting-change-password",
        route: "/settings/security",
        partKey: "security",
        titleKey: "settings.security.changePasswordTitle",
        descriptionKey: "settings.security.changePasswordDesc",
        keywords: [
            "đổi mật khẩu",
            "doi mat khau",
            "mật khẩu",
            "mat khau",
            "password",
            "change password",
            "mật khẩu cũ",
            "mật khẩu mới",
            "xác nhận mật khẩu",
            "bảo mật",
            "security",
            "パスワードの変更",
            "パスワード",
        ],
    },
    {
        id: "current-plan",
        settingId: "setting-current-plan",
        route: "/settings/billing",
        partKey: "billing",
        titleKey: "settings.billing.title",
        descriptionKey: "settings.billing.description",
        keywords: [
            "gói dịch vụ hiện tại",
            "goi dich vu hien tai",
            "gói cước",
            "plan",
            "nâng cấp",
            "nang cap",
            "billing",
            "thanh toán",
            "mua gói",
            "gói dịch vụ",
            "upgrade",
            "subscription",
            "現在のプラン",
            "お支払い",
        ],
    },
];
